"""empty message

Revision ID: bd765364a9d7
Revises:
Create Date: 2021-06-23 14:20:23.734262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = "bd765364a9d7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=0), nullable=True),
        sa.Column("first_name", sa.String(length=60), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column(
            "id_type",
            sa.Enum(
                "national_id", "drivers_license", "passport", "voters_id", name="id_type"
            ),
            nullable=False,
        ),
        sa.Column("id_number", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", "blocked", "first_time", name="status"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "lead",
        sa.Column("id", UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=0), nullable=False),
        sa.Column("first_name", sa.String(length=60), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("id_type", sa.String(length=20), nullable=False),
        sa.Column("id_number", sa.String(length=20), nullable=False),
        sa.Column("otp", sa.String(length=6), nullable=False),
        sa.Column("otp_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_token", sa.String(), nullable=True),
        sa.Column(
            "password_token_expiration", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lead")
    op.drop_table("customer")
    # ### end Alembic commands ###
