"""empty message

Revision ID: fb190f544db0
Revises: ce4983186a96
Create Date: 2021-07-15 09:47:58.071580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb190f544db0"
down_revision = "ce4983186a96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer", sa.Column("auth_token", sa.String(length=6), nullable=True)
    )
    op.add_column(
        "customer",
        sa.Column("auth_token_expiration", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "auth_token_expiration")
    op.drop_column("customer", "auth_token")
    # ### end Alembic commands ###
