# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
      - develop
      - staging
      - main
  pull_request:
    branches:
      - master
      - develop
      - staging
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.4]

    runs-on: self-hosted

    env:
        DB_NAME: test
        TEST_DB_SERVER: .
        FLASK_ENV: testing

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker Image 
      run: docker build --tag manalirahate/nova-gas-customer:1.0.0 . 
      env:
        CI: true
  push_on_docker:
     runs-on: self-hosted
     needs: build
     steps:
         - name: Login to Docker Hub
           uses: docker/login-action@v1
           with: 
#              registry: https://hub.docker.com
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
         - name: Push the Docker Image 
           run: docker push manalirahate/nova-gas-customer:1.0.0
